### ISSUE TITLE
incorrect indentation when adding items above or below

### ISSUE THREAD

**Issue by jschomay** [aserebryakov/vim-todo-lists#15]
Great plugin.  My only problem is that when I am in item editing mode, `o` and `O` insert a new item below/above the current line, but the indentation is one level deeper, instead of at the same level as the current line as I would expect.

Also, when in both modes, pressing enter at the end of an item creates a new item at the left most level (2 spaces) regardless of how far the current line is intended.

I am not sure if this has to do with my shiftwidth/tabstop settings.  I have tried to set them correctly, and they seem to work as expected when I am in normal edit mode.

Has anyone else ran into this issue?  Any ideas?

Thanks!!

**Comment by jakemason** [comment]
I've just made a pull request that addresses this. 

Please see #16

**Comment by aserebryakov** [comment]
Handled by #16
