### ISSUE TITLE
How to uninstall vim-todo-lists?

### ISSUE THREAD

**Issue by arstum** [aserebryakov/vim-todo-lists#23]
I don't know how to uninstall this plugin.

mac 10.14.3
Term
junegunn/vim-plug

Show me follow error when I press "o" after uninstall aserebryakov/vim-todo-lists with junegunn/vim-plug in mac 10.14.3 systerm.

E492: Not an editor command VimTodoListsCreateNewItemBelow

**Comment by the1ts** [comment]
Not really a vim-todo-lists issue, you need to carry out the vim-plug removal process documented at the bottom of the vim-plug tutorial, here https://github.com/junegunn/vim-plug/wiki/tutorial:
Remove the Plug line adding vim-todo-lists, then running :PlugClean in vim.

**Comment by thosakwe** [comment]
You can also just `:mapclear` and then `source $MYVIMRC` if you want to unmap the keybindings (or, just restart Vim).

**Comment by arstum** [comment]
> Not really a vim-todo-lists issue, you need to carry out the vim-plug removal process documented at the bottom of the vim-plug tutorial, here https://github.com/junegunn/vim-plug/wiki/tutorial:
> Remove the Plug line adding vim-todo-lists, then running :PlugClean in vim.

It's not work.

**Comment by arstum** [comment]
It's work after I del the /.vim/view/ folder.

**Comment by arstum** [comment]
> You can also just `:mapclear` and then `source $MYVIMRC` if you want to unmap the keybindings (or, just restart Vim).

It's gone. I have no chance to try it now.
