### ISSUE TITLE
How do I stop displaying command names?

### ISSUE THREAD

**Issue by rogershijin** [aserebryakov/vim-todo-lists#25]
Is there a way to turn off the display of the command name?

![image](https://user-images.githubusercontent.com/27650355/59320842-ca1a8300-8c9d-11e9-82ae-37e9228a0b8d.png)

(:VimTodoListsGoToPreviousItem in the picture)

**Comment by aserebryakov** [comment]
Hi, sorry for late response.

Unfortunately I didn't find a way to find a way to hide it.

**Comment by aserebryakov** [comment]
Merged to dev branch.
