### ISSUE TITLE
Removing the underlining of the  cursor's current line in the buffer

### ISSUE THREAD

**Issue by sfrk** [aserebryakov/vim-todo-lists#41]
![image](https://user-images.githubusercontent.com/84384405/202665791-01a9cf5e-f237-43be-8314-3009ffe5041f.png)

Hi – thanks for writing this very useful plugin. I was wondering if there's a way to remove the underlining of the line in the buffer that the cursor's currently placed on?

**Comment by Jef-coder** [comment]
I don't know that the original author is still active in maintaining this; however, in order to remove the line then you can open up the plugin file and comment out or delete the line that has:
setlocal cursorline

This should remove the underlining in the buffer.

**Comment by sfrk** [comment]
Closing as I've moved on from using this plugin.
